#!/bin/bash

# NextAGI Frontend Environment Setup Script
echo "🚀 Setting up NextAGI Frontend Environment..."

# Create .env.local file
cat > .env.local << EOF
# NextAGI Frontend Environment Configuration
# Generated by setup-env.sh

# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
NEXT_PUBLIC_API_KEY=nextagi_test-key-123

# Development Settings
NODE_ENV=development
EOF

echo "✅ Created .env.local file with default configuration"
echo "📝 Environment variables set:"
echo "   - NEXT_PUBLIC_API_URL=http://localhost:8000"
echo "   - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000" 
echo "   - NEXT_PUBLIC_API_KEY=nextagi_test-key-123"
echo ""
echo "🔧 To customize these values, edit .env.local"
echo "🚀 Ready to run: npm run dev"
